# Generated by Django 4.2.28 on 2026-02-03 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics"),
                            ("Clothing", "Clothing"),
                            ("Books", "Books"),
                            ("Home & Garden", "Home & Garden"),
                            ("Sports", "Sports"),
                            ("Beauty", "Beauty"),
                            ("Toys", "Toys"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("in_stock", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="products_pr_categor_14b9c0_idx"
                    ),
                    models.Index(
                        fields=["in_stock"], name="products_pr_in_stoc_4fee1a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="products_pr_created_52f0d7_idx"
                    ),
                ],
            },
        ),
    ]
